services:
  db:
    image: mysql:8.0
    container_name: test_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - ./DB/mysql:/var/lib/mysql
      - ./db_init/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  postgres:
    image: postgres:14
    container_name: test_postgres
    environment:
      POSTGRES_PASSWORD: root_pg_password
      POSTGRES_DB: test_pgdb
    ports:
      - "5432:5432"
    volumes:
      - ./DB/postgres:/var/lib/postgresql/data
      - ./db_init/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web1:
    build: ./webserver
    container_name: test_webserver1
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./webserver:/app
  web2:
    build: ./webserver
    container_name: test_webserver2
    environment:
      PORT: 8001
    ports:
      - "8001:8001"
    volumes:
      - ./webserver:/app
  web3:
    build: ./webserver
    container_name: test_webserver3
    environment:
      PORT: 8002
    ports:
      - "8002:8002"
    volumes:
      - ./webserver:/app
